jomiel/keygen/app: replace nargs="+" with filename count check
Replace nargs="+" with nargs="*" and check the filename count in our
code rather than having configargparse (argparse?) do this for us.

Having nargs="+" would cause funny issues in cases like:
  $ jomiel-keygen -v
  error: the following arguments are required: filename

While it would work fine in cases like:
  $ jomiel-keygen --version